variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - precheck
  - build 
  - benchmark

build-thesis:
  stage: precheck
  only:
    - main
    - staging
    - thesis
  tags:
    - imt-no-sla
  image: "texlive/texlive"
  script:
    - "cd docs/thesis"
    - "latexmk --pdf thesis.tex"
    - "cd ../proposal"
    - "latexmk --pdf proposal.tex"
  artifacts:
    paths:
      - "docs/thesis/thesis.pdf"
      - "docs/proposal/proposal.pdf"
    expire_in: 1 month

generate inputs:
  stage: build
  only:
    - main
    - staging
    - cpu_scoring_benchmark
  tags:
    - imt-no-sla
  image: "python"
  script:
    - "python3 -m venv .venv"
    - "source .venv/bin/activate"
    - "pip install --upgrade pip"
    - "pip install -r requirements.txt"
    - "./scripts/performance_benchmark/generate_inputs.sh"
    - "./scripts/quality_benchmark/generate_inputs.sh"
  artifacts:
    paths:
      - "performance_benchmark.out"
      - "quality_benchmark.out"

cpu scoring benchmark noctua2:
  stage: benchmark
  only:
    - main
    - staging
    - cpu_scoring_benchmark
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 00:20:00 --exclusive"
    DPCPP_CPU_NUM_CUS: 128
  script:
    - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    - "mkdir -p build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release -DPC2_SYSTEM=Noctua2 .."
    - "VERBOSE=1 make cpu_scoring_benchmark"
    - "perf stat -e instructions,ex_ret_mmx_fp_instr.sse_instr,L1-dcache-load-misses,L1-dcache-loads
        ./cpu_scoring_benchmark/cpu_scoring_benchmark -i ../performance_benchmark.out/128/input.csv -r 128 -l 10000000"
  artifacts:
    paths:
      - "build/cpu_scoring_benchmark/cpu_scoring_benchmark"

cpu scoring benchmark noctua1:
  stage: benchmark
  only:
    - main
    - staging
    - cpu_scoring_benchmark
  tags:
    - noctua1
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 00:20:00 --exclusive"
    DPCPP_CPU_NUM_CUS: 40
  script:
    - "ml toolchain devel intel/2022b Boost CMake"
    - "mkdir -p build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release -DPC2_SYSTEM=Noctua1 .."
    - "VERBOSE=1 make cpu_scoring_benchmark"
    - "perf stat -e instructions,L1-dcache-load-misses,L1-dcache-loads
        ./cpu_scoring_benchmark/cpu_scoring_benchmark -i ../performance_benchmark.out/128/input.csv -r 40 -l 2500000"
  artifacts:
    paths:
      - "build/cpu_scoring_benchmark/cpu_scoring_benchmark"
