variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - precheck
  - build 
  - benchmark

build-thesis:
  stage: precheck
  only:
    - main
    - staging
    - thesis
  image: "texlive/texlive"
  script:
    - "cd docs/thesis"
    - "latexmk --pdf thesis.tex"
    - "cd ../proposal"
    - "latexmk --pdf proposal.tex"
  artifacts:
    paths:
      - "docs/thesis/thesis.pdf"
      - "docs/proposal/proposal.pdf"
    expire_in: 1 month
  tags:
    - docker

build-cpu-scoring-benchmark:
  stage: build
  only:
    - cpu_scoring_benchmark
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 00:05:00 -c 1 --mem 8G"
  script:
    - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    - "mkdir -p build"
    - "cd build"
    - "python3 -m venv .venv"
    - "source .venv/bin/activate"
    - "pip install --upgrade pip"
    - "pip install -r ../requirements.txt"
    - "../tool.py generate -o . -n 63 -m 64 -a 1e-6 -b 0.42 -e 0.4"
    - "cmake -DCMAKE_BUILD_TYPE=Release .."
    - "make cpu_scoring_benchmark"
  artifacts:
    paths:
      - "build/input.csv"
      - "build/cpu_scoring_benchmark/cpu_scoring_benchmark"

run-cpu-scoring-benchmark:
  stage: benchmark
  only:
    - cpu_scoring_benchmark
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 00:20:00 -c 16 --mem 16G"
    DPCPP_CPU_NUM_CUS: 16
  script:
    - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    - "cd build"
    - "./cpu_scoring_benchmark/cpu_scoring_benchmark -i input.csv -r 32 -l 10000000"
