build-documents:
  stage: build
  image: "texlive/texlive:latest"
  script:
    - "cd proposal"
    - "latexmk --pdf proposal"
    - "cd ../thesis"
    - "latexmk --pdf thesis"
  artifacts:
    paths:
    - "proposal/proposal.pdf"
    - "thesis/thesis.pdf"
  tags:
    - shared

build-tests:
  stage: build
  image: "intel/oneapi-basekit:devel-ubuntu18.04"
  script:
    - "source /opt/intel/oneapi/setvars.sh"
    - "mkdir build"
    - "cd build"
    - "cmake .."
    - "make -j$(nproc) test"
    - "./test/test"
  tags:
    - shared
