variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - benchmark
  - evaluate

default:
  before_script:
    - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    - "python3 -m venv .venv"
    - "source .venv/bin/activate"
    - "pip install --upgrade pip"
    - "pip install -r requirements.txt"

build thesis:
  stage: build
  needs: []
  only:
    - main
    - staging
  tags:
    - imt-no-sla
  image: "texlive/texlive"
  before_script: []
  script:
    - "cd docs/thesis"
    - "latexmk --pdf thesis.tex"
    - "cd ../proposal"
    - "latexmk --pdf proposal.tex"
  artifacts:
    paths:
      - "docs/thesis/thesis.pdf"
      - "docs/proposal/proposal.pdf"
    expire_in: 1 month

generate inputs & build scite:
  stage: build
  only:
    - main
    - staging
  needs: []
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal  -t 00:15:00 -c 16 --mem=8G"
  script:
    - "./scripts/performance_benchmark/generate_inputs.sh"
    - "./scripts/quality_benchmark/generate_inputs.sh"
    - "mkdir -p build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release .."
    - "make -j16 scite"
  artifacts:
    paths:
      - "performance_benchmark.out"
      - "quality_benchmark.out"
      - "build/scite"

build ffscite64:
  stage: build
  only:
    - main
    - staging
  when: manual
  needs: []
  allow_failure: false
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem=100G"
  script:
    - "mkdir -p build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release -DPC2_SYSTEM=Noctua2 .."
    - "VERBOSE=1 make ffSCITE64"
  artifacts:
    when: always
    paths:
      - "build/src/ffSCITE64"
      - "build/src/ffSCITE64.prj/reports"
      - "build/src/ffSCITE64.prj/quartus_sh_compile.log"

build ffscite96:
  stage: build
  only:
    - main
    - staging
  when: manual
  needs: []
  allow_failure: false
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem=100G"
  script:
    - "mkdir -p build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release -DPC2_SYSTEM=Noctua2 .."
    - "VERBOSE=1 make ffSCITE96"
  artifacts:
    when: always
    paths:
      - "build/src/ffSCITE96"
      - "build/src/ffSCITE96.prj/reports"
      - "build/src/ffSCITE96.prj/quartus_sh_compile.log"

build ffscite128:
  stage: build
  only:
    - main
    - staging
  when: manual
  needs: []
  allow_failure: false
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem=100G"
  script:
    - "mkdir -p build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release -DPC2_SYSTEM=Noctua2 .."
    - "VERBOSE=1 make ffSCITE128"
  artifacts:
    when: always
    paths:
      - "build/src/ffSCITE128"
      - "build/src/ffSCITE128.prj/reports"
      - "build/src/ffSCITE128.prj/quartus_sh_compile.log"

benchmark ffscite:
  stage: benchmark
  only:
    - main
    - staging
  needs: 
    - "build ffscite64"
    - "build ffscite96"
    - "build ffscite128"
    - "generate inputs & build scite"
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p fpga --constraint=bittware_520n_20.4.0_hpc -t 03:00:00"
  script:
    - "./scripts/quality_benchmark/ffscite.sh"
    - "./scripts/performance_benchmark/ffscite.sh"
  artifacts:
    paths:
      - "quality_benchmark.out/*/ffSCITE64"
      - "quality_benchmark.out/*/ffSCITE96"
      - "quality_benchmark.out/*/ffSCITE128"
      - "performance_benchmark.out/*/ffSCITE"

benchmark scite:
  stage: benchmark
  only:
    - main
    - staging
  needs: 
    - "generate inputs & build scite"
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -c 64 -t 04:00:00"
  script:
    - "./scripts/quality_benchmark/scite.sh"
    - "./scripts/performance_benchmark/scite.sh"
  artifacts:
    paths:
      - "quality_benchmark.out/*/SCITE"
      - "performance_benchmark.out/*/SCITE"

benchmark cpu scoring on noctua2:
  stage: benchmark
  only:
    - main
    - staging
  needs: 
    - "generate inputs & build scite"
  tags:
    - noctua2
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 00:20:00 --exclusive"
    DPCPP_CPU_NUM_CUS: 128
  before_script:
    - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
  script:
    - "mkdir -p build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release -DPC2_SYSTEM=Noctua2 .."
    - "VERBOSE=1 make cpu_scoring_benchmark cpu_scoring_offload"
    - "perf stat -e instructions,ex_ret_mmx_fp_instr.sse_instr,L1-dcache-load-misses,L1-dcache-loads
        ./cpu_scoring_benchmark/cpu_scoring_benchmark -i ../performance_benchmark.out/128/input.csv -r 128 -l 10000000"
  artifacts:
    paths:
      - "build/cpu_scoring_benchmark/cpu_scoring_benchmark"
      - "build/cpu_scoring_benchmark/cpu_scoring_offload.asm"

benchmark cpu scoring on noctua1:
  stage: benchmark
  only:
    - main
    - staging
  needs: 
    - "generate inputs & build scite"
  tags:
    - noctua1
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 00:20:00 --exclusive"
    DPCPP_CPU_NUM_CUS: 40
  before_script:
    - "ml toolchain devel intel/2022b Boost CMake"
  script:
    - "mkdir -p build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release -DPC2_SYSTEM=Noctua1 .."
    - "VERBOSE=1 make cpu_scoring_benchmark cpu_scoring_offload"
    - "perf stat -e instructions,L1-dcache-load-misses,L1-dcache-loads
        ./cpu_scoring_benchmark/cpu_scoring_benchmark -i ../performance_benchmark.out/128/input.csv -r 40 -l 2500000"
  artifacts:
    paths:
      - "build/cpu_scoring_benchmark/cpu_scoring_benchmark"
      - "build/cpu_scoring_benchmark/cpu_scoring_offload.asm"