variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - precheck
  - synthesis
  - benchmark

default:
  before_script:
    - "ml fpga devel intel/oneapi bittware/520n Boost/1.74.0-GCC CMake"
    - "mkdir -p build"
    - "cd build"

build-thesis:
  stage: precheck
  image: "texlive/texlive"
  before_script: []
  script:
    - "cd docs/thesis"
    - "latexmk --pdf thesis.tex"
    - "cd ../proposal"
    - "latexmk --pdf proposal.tex"
  artifacts:
    paths:
      - "docs/thesis/thesis.pdf"
      - "docs/proposal/proposal.pdf"
    expire_in: 1 month
  tags:
    - sencha

unit-tests:
  stage: precheck
  script:
    - "cmake -DCMAKE_BUILD_TYPE=Release .."
    - "make -j16 unit_test"
    - "./test/unit_test"
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal --time=00:10:00 --mem 8G --cpus-per-task=16"
  tags:
    - noctua2

synthesis:
  stage: synthesis
  only:
    - main
  script:
    - "cmake -DCMAKE_BUILD_TYPE=Release .."
    - "make -j64 scite"
    - "dpcpp -fintelfpga -qactypes -Xshardware -Xsv -Xsparallel=64 ../src/main.cpp -o ffSCITE"
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -q fpgasynthesis --time=2-00:00:00 --cpus-per-task=64 --mail-type=All --mail-user=joo@mail.upb.de"
  artifacts:
    paths:
      - "build/ffSCITE.prj/reports"
      - "build/ffSCITE"
      - "build/scite"
    expire_in: 1 month
  tags:
    - noctua2

report:
  stage: synthesis
  when: manual
  script:
    - "dpcpp -fintelfpga -qactypes -fsycl-link -Xshardware -Xsv -Xsparallel=16 ../src/main.cpp -o ffSCITE"
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal --time=01:00:00 --mem 32G --cpus-per-task=16"
  artifacts:
    paths:
      - "build/ffSCITE.prj/reports"
    expire_in: 1 month
  tags:
    - noctua2

quality benchmark:
  stage: benchmark
  only:
    - main
  dependencies:
    - synthesis
  script:
    - "../experiments/quality_benchmark.sh ./scite ./ffSCITE"
    - "./tool.py test"
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal --time=12:00:00 --cpus-per-task=128"
  artifacts:
    paths:
      - "build/quality_benchmark.out"
  tags:
    - noctua2
