variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - precheck
  - synthesis
  - benchmark

unit-tests:
  only:
    - main
    - staging
  stage: precheck
  script:
    - "ml fpga devel intel/oneapi bittware/520n Boost/1.76.0-GCC CMake"
    - "mkdir build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release .."
    - "make -j16 unit_test"
    - "./test/unit_test"
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal --time=00:05:00 --mem 2G --cpus-per-task=16"
  tags:
    - noctua2

synthesis:
  only:
    - main
  stage: synthesis
  dependencies:
    - unit-tests
  script:
    - "ml fpga devel intel/oneapi bittware/520n Boost/1.76.0-GCC CMake"
    - "mkdir build"
    - "cd build"
    - "cmake -DCMAKE_BUILD_TYPE=Release .."
    - "make -j8 ffSCITE_emu scite"
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal --time=00:02:00 --mem 2G --cpus-per-task=8"
  artifacts:
    paths:
      - "build/src/ffSCITE_emu"
      - "build/scite"
  tags:
    - noctua2

report:
  only:
    - main
  stage: benchmark # This is only temporary, until the synthesis job takes longer than the report job. Then, it will be "precheck" again
  script:
    - "ml fpga devel"
    - "ml intel/oneapi bittware/520n Boost/1.76.0-GCC CMake"
    - "mkdir build"
    - "cd build"
    - "dpcpp -fintelfpga -qactypes -fsycl-link -Xshardware -Xsv ../src/main.cpp -o ffSCITE"
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal --time=00:30:00 --mem 32G --cpus-per-task=32"
  artifacts:
    paths:
      - "build/ffSCITE.prj/reports"
    expire_in: 1 month
  tags:
    - noctua2

quality benchmark:
  only:
    - main
  stage: benchmark
  dependencies:
    - synthesis
  script:
    - "module reset"
    - "ml fpga devel intel/oneapi bittware/520n Boost/1.76.0-GCC CMake"
    - "python3 -m venv .venv"
    - "source .venv/bin/activate"
    - "pip install --upgrade pip"
    - "pip install -r requirements.txt"
    - "./experiments/quality_benchmark.sh ./build/scite ./build/src/ffSCITE_emu"
    - "./tool.py test"
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal --time=12:00:00 --cpus-per-task=128"
  artifacts:
    paths:
      - "quality_benchmark.out"
  tags:
    - noctua2
