build-documents:
  only:
    - main
  stage: build
  image: "texlive/texlive:latest"
  script:
    - "cd proposal"
    - "latexmk --pdf proposal"
    - "cd ../thesis"
    - "latexmk --pdf thesis"
  artifacts:
    paths:
    - "proposal/proposal.pdf"
    - "thesis/thesis.pdf"
  tags:
    - shared

build-tests:
  only:
    - main
  stage: build
  script:
    - "ml devel/Boost devel/CMake compiler/GCC nalla_pcie intel/oneAPI"
    - "mkdir build"
    - "cd build"
    - "cmake .."
    - "make -j$(nproc) unit_test"
    - "./test/unit_test"
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p short --time=00:05:00"
  tags:
    - noctua
