variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - precheck
  - synthesis

default:
  before_script:
    - "ml fpga devel intel/oneapi bittware/520n Boost/1.79.0-GCC CMake"
    - "mkdir -p build"
    - "cd build"

build-thesis:
  stage: precheck
  only:
    - main
    - staging
    - thesis
  image: "texlive/texlive"
  before_script: []
  script:
    - "cd docs/thesis"
    - "latexmk --pdf thesis.tex"
    - "cd ../proposal"
    - "latexmk --pdf proposal.tex"
  artifacts:
    paths:
      - "docs/thesis/thesis.pdf"
      - "docs/proposal/proposal.pdf"
    expire_in: 1 month
  tags:
    - docker

