build-documents:
  stage: build
  image: "texlive/texlive:latest"
  script:
    - "cd proposal"
    - "latexmk --pdf proposal"
    - "cd ../thesis"
    - "latexmk --pdf thesis"
  artifacts:
    paths:
    - "proposal/proposal.pdf"
    - "thesis/thesis.pdf"
  tags:
    - shared

simple-test:
  stage: build
  image: "alpine:latest"
  script:
    - "echo 'Hallo Welt!' > test.txt"
  artifacts:
    path:
    - "test.txt"
  tags:
    - shared